spring:
  application:
    name: tiki-cloned
  datasource:
    url: jdbc:mariadb://localhost:3306/tiki-cloned
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  liquibase:
    change-log: db.changelog/changelog-master.xml
    enabled: true
---
app:
  version: 0.0.1
  secretKey: abc
  refreshSecretKey: 123
  expiredTime: 100
  refreshExpiredTime: 100000
---

